app = "quest-game-server"

kill_signal = "SIGINT"
kill_timeout = 5

[build]
  dockerfile = "./Dockerfile"

[env]
  NODE_ENV = "production"

[[services]]
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
